language: node_js
node_js:
- '0.11'
deploy:
  provider: npm
  email: sqrt@octoblu.com
  api_key:
    secure: RLwVRknCKH12eakFCVeg4qmBOs8sQqb0ZlVck7oHAhAa/N5dGK/C6WFcrpfRcekFGS0lhygZLQtGfyADCXM0xBoxAaCkEXy98Ts7LuPiaMpb9dZwQ3DyOKzTWfQRu/mSjWxfQWTXVMV7K8azSjhm717UYFOlEmxQ9BB2sJ+2wGmoeRhvt9IudU0DPkxvzL/eUjZVG250Al2gJI+bFJC0TVaHsCZYiSEhTdrFCWHgsW82o7eBbXVefdWEQzdqPcMIGJPYQDAmr5A8r6WltSlouSNZmGxVeXI9AacGDlNWjrP59JRcV5LFYTl1IhCvmw3tb85K6PVSW92FfcNdluMSLINn8y6baJ6+lR3ZxMqP2sCieXmxonVeIGfkgKeLOZ8SGwIt6vyGWXhddH8uu92LNYAI1gN8CBLC1nfKDaEr/1k4oolhxEO4FpdertQSB6nPfPU3mJ6jcHUhhBkVDxZFDPhMw8ufahGWofPh8kzggPb2KlH642+x29b8m877DPTVbl4v2hCaIbqJg5FUnZRDVy/5YAtUun81xWezvuTM3hJsPIpP4gdVXMlumxj4Zb4aw/Qw1IgeWQHRW8Od9hKjHcvSwRPZ9Dk6m5LSikSTEZxcS/B3uwhzlidU3cmP0snCD1MlSz219YguPffkKZmyQm4E7FVLEX5+Iy1jXc6Zgxg=
  on:
    tags: true
    all_branches: true
